modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="create_central_kitchen" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Create: Central Kitchen"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="LimonBlaze, MarbleGate and Etherwood"
description='''
An add-on for Create, providing automation support for Farmer's Delight and its add-ons.
'''

[[dependencies.create_central_kitchen]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_central_kitchen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_central_kitchen]]
    modId="create"
    mandatory=true
    versionRange="[0.5.0.i,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_central_kitchen]]
    modId="farmersdelight"
    mandatory=false
    versionRange="[1.18.2-1.2.0,)"
    ordering="NONE"
    side="BOTH"